language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

licenses:
 - android-sdk-license-.+

branches:
  only:
  - master
  - develop

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./script/check.sh
  - ./script/sonar_scan.sh
